
<!-- app/code/LandingPage/Form/view/frontend/templates/guest.phtml -->

<?php
/** @var LandingPage\Form\Block\Index $block */

?>

<div  style="display:flex;justify-content:center;align-items:center;"class="product-hero__content" x-data="{ seeMore: false }">

    <h2 class="product-hero__title">
        <!-- Add Product Name -->
        <?= __("The module is disabled or not supported on this store.") ?>      </h2>
   