<!-- app/code/LandingPage/Form/view/frontend/templates/content.phtml -->

<?php
/** @var LandingPage\Form\Block\Index $block */

?>
<div class="landing-page-content">
    <?php   if($block->isModuleEnabled() && $block->isEnglishStore()):  ?>
        <?php if($block->isCustomerLoggerIn()): ?>
            <?= $block->getChildHtml('form_block_child_form'); ?>
        <?php else: ?>
            <?= $block->getChildHtml('form_block_child_session'); ?>
        <?php endif; ?>



    <?php else: ?> 
        <?= $block->getChildHtml('form_block_child_disabled'); ?>   
    <?php endif; ?>
</div>